secret:
  create: false

postgresql:
  enabled: false

sealedSecret:
  enabled: true
  encryptedData:
    DATABASE_URL: ""
    KAFKA_BROKERS: ""
    KAFKA_SASL_USERNAME: ""
    KAFKA_SASL_PASSWORD: ""
    PUBSUB_PROJECT_ID: ""