{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "outbox-dispatch.secretName" . }}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedSecret.encryptedData.DATABASE_URL | quote }}
    KAFKA_BROKERS: {{ .Values.sealedSecret.encryptedData.KAFKA_BROKERS | quote }}
    KAFKA_SASL_USERNAME: {{ .Values.sealedSecret.encryptedData.KAFKA_SASL_USERNAME | quote }}
    KAFKA_SASL_PASSWORD: {{ .Values.sealedSecret.encryptedData.KAFKA_SASL_PASSWORD | quote }}
    PUBSUB_PROJECT_ID: {{ .Values.sealedSecret.encryptedData.PUBSUB_PROJECT_ID | quote }}
  template:
    metadata:
      name: {{ include "outbox-dispatch.secretName" . }}
    type: Opaque
{{- end }}