import { getServerSession } from 'next-auth'
import { NextRequest } from 'next/server'

import { getSessionSignatures } from '@/lib/agents/clinical-signature'
import type { ClinicalSignatureRecord } from '@/lib/agents/clinical-signature'
import { authOptions } from '@/lib/auth'
import { db } from '@/lib/db'

type RouteContext = {
  params: Promise<{ id: string }>
}

type AgentResultPayload = {
  sessionId: string
  status: string
  plan: {
    goal: string
    steps: { agentClass: string; description: string; status: string; durationMs?: number }[]
  }
  summary?: string
  safetyFlags: { severity: string; description: string; source: string }[]
  startedAt: string
  completedAt?: string
  totalDurationMs?: number
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function buildPhysicianSummary(
  result: AgentResultPayload,
  userName: string | null,
  userEmail: string,
  signatures: ClinicalSignatureRecord[],
): string {
  const lines: string[] = []

  lines.push('═══════════════════════════════════════════════════════════')
  lines.push('        BIOZEPHYRA AI — PHYSICIAN SUMMARY REPORT')
  lines.push('═══════════════════════════════════════════════════════════')
  lines.push('')
  lines.push(`Patient:        ${userName ?? 'N/A'}`)
  lines.push(`Contact:        ${userEmail}`)
  lines.push(`Report Date:    ${formatDate(new Date().toISOString())}`)
  lines.push(`Session ID:     ${result.sessionId}`)
  lines.push(`Analysis Date:  ${formatDate(result.startedAt)}`)
  if (result.completedAt) {
    lines.push(`Completed:      ${formatDate(result.completedAt)}`)
  }
  lines.push(`Status:         ${result.status.toUpperCase()}`)
  lines.push('')
  lines.push('───────────────────────────────────────────────────────────')
  lines.push('ANALYSIS GOAL')
  lines.push('───────────────────────────────────────────────────────────')
  lines.push(result.plan.goal)
  lines.push('')

  // Agent pipeline summary
  lines.push('───────────────────────────────────────────────────────────')
  lines.push('ANALYSIS PIPELINE')
  lines.push('───────────────────────────────────────────────────────────')
  for (const step of result.plan.steps) {
    const statusIcon =
      step.status === 'completed' ? '[OK]' : step.status === 'failed' ? '[FAIL]' : `[${step.status.toUpperCase()}]`
    const duration = step.durationMs ? ` (${step.durationMs}ms)` : ''
    lines.push(`  ${statusIcon} ${step.agentClass.toUpperCase()}: ${step.description}${duration}`)
  }
  lines.push('')

  // Main findings
  if (result.summary) {
    lines.push('───────────────────────────────────────────────────────────')
    lines.push('FINDINGS & RECOMMENDATIONS')
    lines.push('───────────────────────────────────────────────────────────')
    lines.push(result.summary)
    lines.push('')
  }

  // Safety flags
  if (result.safetyFlags.length > 0) {
    lines.push('───────────────────────────────────────────────────────────')
    lines.push('SAFETY ALERTS')
    lines.push('───────────────────────────────────────────────────────────')
    for (const flag of result.safetyFlags) {
      const level = flag.severity.toUpperCase()
      lines.push(`  [${level}] ${flag.description} (source: ${flag.source})`)
    }
    lines.push('')
  }

  // Clinical Signatures
  if (signatures.length > 0) {
    lines.push('───────────────────────────────────────────────────────────')
    lines.push('CLINICAL SIGNATURES')
    lines.push('───────────────────────────────────────────────────────────')
    lines.push('')
    lines.push('The following recommendations were reviewed and approved')
    lines.push('by a licensed clinician with a verified digital signature:')
    lines.push('')

    for (const sig of signatures) {
      lines.push(`  Compound:    ${sig.compoundName ?? 'N/A'}`)
      lines.push(`  Risk Tier:   ${sig.riskCategory ?? 'N/A'}`)
      lines.push(`  Clinician:   ${sig.clinicianName}`)
      lines.push(`  Contact:     ${sig.clinicianEmail}`)
      lines.push(`  Rationale:   ${sig.rationale}`)
      lines.push(`  Signed At:   ${formatDate(sig.signedAt)}`)
      lines.push(`  Signature:   ${sig.signatureHash}`)
      lines.push('')
    }

    lines.push('  Signature hashes are SHA-256 digests binding the')
    lines.push('  clinician identity, review item, rationale, and')
    lines.push('  timestamp. They can be independently verified against')
    lines.push('  the Biozephyra audit trail.')
    lines.push('')
  }

  // Disclaimer
  lines.push('───────────────────────────────────────────────────────────')
  lines.push('DISCLAIMER')
  lines.push('───────────────────────────────────────────────────────────')
  lines.push('This report was generated by Biozephyra AI, an automated')
  lines.push('multi-agent longevity analysis platform. The findings and')
  lines.push('recommendations are algorithmically derived and should be')
  lines.push('reviewed by a licensed healthcare provider before any')
  lines.push('clinical decisions are made. This report does not')
  lines.push('constitute medical advice, diagnosis, or treatment.')
  lines.push('')
  lines.push('Biozephyra AI employs safety-gated agents with clinician-')
  lines.push('in-the-loop review for all high-severity recommendations.')
  lines.push('')
  lines.push('═══════════════════════════════════════════════════════════')
  lines.push(`Generated: ${formatDate(new Date().toISOString())}`)
  lines.push('═══════════════════════════════════════════════════════════')

  return lines.join('\n')
}

/**
 * GET /api/agents/session/[id]/export
 *
 * Generates a Physician Summary report from a completed agent session.
 * Returns plain-text content with Content-Disposition for download.
 */
export async function GET(_request: NextRequest, context: RouteContext) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) {
    return new Response('Unauthorized', { status: 401 })
  }

  const { id: sessionId } = await context.params

  const agentSession = await db.agentSession.findUnique({
    where: { id: sessionId },
    select: {
      userId: true,
      result: true,
      status: true,
      user: { select: { name: true, email: true } },
    },
  })

  if (!agentSession) {
    return new Response('Session not found', { status: 404 })
  }

  if (agentSession.userId !== session.user.id) {
    return new Response('Forbidden', { status: 403 })
  }

  if (!agentSession.result) {
    return new Response('Session has no results yet', { status: 400 })
  }

  const resultPayload = JSON.parse(agentSession.result) as AgentResultPayload

  // Fetch clinical signatures for this session
  const signatures = await getSessionSignatures(sessionId)

  const report = buildPhysicianSummary(
    resultPayload,
    agentSession.user.name,
    agentSession.user.email,
    signatures,
  )

  const fileName = `biozephyra-physician-summary-${sessionId.slice(0, 8)}.txt`

  return new Response(report, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Cache-Control': 'private, no-cache',
    },
  })
}
