import { AppShell } from "@/components/app-shell"

export default function DisclaimerPage() {
  return (
    <AppShell>
      <div className="min-h-full bg-gray-900">
      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-white mb-8">Medical Disclaimer</h1>

        <div className="prose prose-invert prose-gray max-w-none space-y-6 text-gray-300 text-sm leading-relaxed">
          <div className="bg-yellow-900/20 border border-yellow-800 rounded-lg p-4 mb-8">
            <p className="text-yellow-300 font-semibold text-base">Important</p>
            <p className="text-yellow-200/80 mt-1">
              Biozephyra is an educational and research platform. It is <strong>not</strong> a medical device,
              diagnostic tool, or healthcare provider.
            </p>
          </div>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Not Medical Advice</h2>
            <p>
              Information provided on this platform — including compound data, pathway descriptions, biomarker references,
              clinical trial listings, and AI-generated responses — is for <strong>educational and research purposes only</strong>.
              Nothing on Biozephyra constitutes medical advice, diagnosis, or treatment recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Consult Healthcare Professionals</h2>
            <p>
              Before starting, stopping, or modifying any supplement, medication, or health protocol, consult a qualified
              healthcare professional. Do not rely on information from this platform for medical decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Research Data Accuracy</h2>
            <p>
              Compound interaction data, biomarker effects, and research citations are sourced from public databases
              (PubMed, ClinicalTrials.gov) and curated knowledge graphs. While we strive for accuracy, scientific
              understanding evolves and data may be incomplete, outdated, or incorrectly categorized.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">AI-Generated Content</h2>
            <p>
              Responses from AI features (health coach, recommendations) are generated by language models and may contain
              inaccuracies. AI output should never be treated as authoritative medical guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Medical Emergencies</h2>
            <p>
              Biozephyra is <strong>not</strong> for medical emergencies. If you think you may have a medical emergency,
              call your doctor or your local emergency number (such as 911 in the United States) immediately. Do not rely
              on this platform for urgent or emergency medical needs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">No Doctor–Patient Relationship</h2>
            <p>
              Using Biozephyra does not create a doctor–patient, physician, or other professional relationship between you
              and Biozephyra. Any telemedicine consultations, lab orders, or clinician interactions facilitated through the
              platform are provided by independent, licensed third-party providers who are solely responsible for the care
              they deliver. Biozephyra does not practice medicine and does not supervise those providers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Dietary Supplements &amp; FDA Statement</h2>
            <p>
              Statements regarding compounds, supplements, or dietary ingredients have <strong>not</strong> been evaluated
              by the U.S. Food and Drug Administration (FDA) or any comparable regulator. Products and information referenced
              on this platform are not intended to diagnose, treat, cure, or prevent any disease. Regulatory status of any
              compound varies by jurisdiction and may change.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Assumption of Risk &amp; No Liability</h2>
            <p>
              You use Biozephyra and any information accessed through it entirely at your own risk. To the maximum extent
              permitted by law, Biozephyra and its operators, officers, and affiliates are not liable for any adverse health
              effects, injuries, losses, or damages — direct or indirect — arising from your use of, or reliance on, the
              platform or its content.
            </p>
          </section>
        </div>
      </main>
    </div>
    </AppShell>
  )
}
