import { AppShell } from "@/components/app-shell"

export default function DisclaimerPage() {
  return (
    <AppShell>
      <div className="min-h-full bg-gray-900">
      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-white mb-8">Medical Disclaimer</h1>

        <div className="prose prose-invert prose-gray max-w-none space-y-6 text-gray-300 text-sm leading-relaxed">
          <div className="bg-yellow-900/20 border border-yellow-800 rounded-lg p-4 mb-8">
            <p className="text-yellow-300 font-semibold text-base">Important</p>
            <p className="text-yellow-200/80 mt-1">
              Biozephyra is an educational and research platform. It is <strong>not</strong> a medical device,
              diagnostic tool, or healthcare provider.
            </p>
          </div>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Not Medical Advice</h2>
            <p>
              Information provided on this platform — including compound data, pathway descriptions, biomarker references,
              clinical trial listings, and AI-generated responses — is for <strong>educational and research purposes only</strong>.
              Nothing on Biozephyra constitutes medical advice, diagnosis, or treatment recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Consult Healthcare Professionals</h2>
            <p>
              Before starting, stopping, or modifying any supplement, medication, or health protocol, consult a qualified
              healthcare professional. Do not rely on information from this platform for medical decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">Research Data Accuracy</h2>
            <p>
              Compound interaction data, biomarker effects, and research citations are sourced from public databases
              (PubMed, ClinicalTrials.gov) and curated knowledge graphs. While we strive for accuracy, scientific
              understanding evolves and data may be incomplete, outdated, or incorrectly categorized.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">AI-Generated Content</h2>
            <p>
              Responses from AI features (health coach, recommendations) are generated by language models and may contain
              inaccuracies. AI output should never be treated as authoritative medical guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-3">No Liability</h2>
            <p>
              Biozephyra and its operators are not liable for any adverse health effects, injuries, or damages arising
              from the use of information on this platform. Use at your own risk.
            </p>
          </section>
        </div>
      </main>
    </div>
    </AppShell>
  )
}
